"""Add enrichment history

Revision ID: 3386a5921a08
Revises: bb3e3aefbc60
Create Date: 2026-03-29 09:12:44.193587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3386a5921a08'
down_revision: Union[str, None] = 'bb3e3aefbc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ioc_value', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=False),
    sa.Column('overall_verdict', sa.String(), nullable=False),
    sa.Column('threat_summary', sa.String(), nullable=True),
    sa.Column('full_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_history_created_at'), 'enrichment_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrichment_history_id'), 'enrichment_history', ['id'], unique=False)
    op.create_index(op.f('ix_enrichment_history_ioc_value'), 'enrichment_history', ['ioc_value'], unique=False)
    op.create_index(op.f('ix_enrichment_history_user_id'), 'enrichment_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_history_user_id'), table_name='enrichment_history')
    op.drop_index(op.f('ix_enrichment_history_ioc_value'), table_name='enrichment_history')
    op.drop_index(op.f('ix_enrichment_history_id'), table_name='enrichment_history')
    op.drop_index(op.f('ix_enrichment_history_created_at'), table_name='enrichment_history')
    op.drop_table('enrichment_history')
    # ### end Alembic commands ###
