"""Add alerts v2

Revision ID: 913c2621f06a
Revises: cd302b189557
Create Date: 2026-03-29 11:15:11.541606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913c2621f06a'
down_revision: Union[str, None] = 'cd302b189557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_sectors', sa.JSON(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_groups_id'), 'mitre_groups', ['id'], unique=False)
    op.create_table('mitre_software',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_software_id'), 'mitre_software', ['id'], unique=False)
    op.create_table('mitre_tactics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shortname', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_tactics_id'), 'mitre_tactics', ['id'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('is_subtechnique', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('frequency_score', sa.Integer(), nullable=True),
    sa.Column('linked_cve_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_id'), 'mitre_techniques', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rule_type', sa.Enum('CVE_SEVERITY', 'IP_ABUSE_SCORE', 'KEYWORD_MATCH', 'TTP_DETECTED', 'KEV_ADDED', name='ruletype'), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('mitre_group_software',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('software_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['mitre_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['mitre_software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'software_id')
    )
    op.create_table('mitre_group_technique',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['mitre_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'technique_id')
    )
    op.create_table('mitre_software_technique',
    sa.Column('software_id', sa.String(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['mitre_software.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('software_id', 'technique_id')
    )
    op.create_table('mitre_technique_tactic',
    sa.Column('tactic_id', sa.String(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_tactics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tactic_id', 'technique_id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('ioc_id', sa.String(), nullable=True),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'DISMISSED', name='alertstatus'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('mitre_technique_tactic')
    op.drop_table('mitre_software_technique')
    op.drop_table('mitre_group_technique')
    op.drop_table('mitre_group_software')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_mitre_techniques_id'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_mitre_tactics_id'), table_name='mitre_tactics')
    op.drop_table('mitre_tactics')
    op.drop_index(op.f('ix_mitre_software_id'), table_name='mitre_software')
    op.drop_table('mitre_software')
    op.drop_index(op.f('ix_mitre_groups_id'), table_name='mitre_groups')
    op.drop_table('mitre_groups')
    # ### end Alembic commands ###
