"""Add Phase 2 IOC pipeline models

Revision ID: bb3e3aefbc60
Revises: 3e06df65628f
Create Date: 2026-03-29 09:01:06.366638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3e3aefbc60'
down_revision: Union[str, None] = '3e06df65628f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cves',
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_severity', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=True),
    sa.Column('cwe_ids', sa.JSON(), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_index(op.f('ix_cves_cve_id'), 'cves', ['cve_id'], unique=False)
    op.create_index(op.f('ix_cves_is_kev'), 'cves', ['is_kev'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('IP', 'DOMAIN', 'URL', 'HASH_MD5', 'HASH_SHA256', 'CVE', name='ioctype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iocs_id'), 'iocs', ['id'], unique=False)
    op.create_index(op.f('ix_iocs_type'), 'iocs', ['type'], unique=False)
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=True)
    op.create_table('threat_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('total_iocs', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_feeds_id'), 'threat_feeds', ['id'], unique=False)
    op.create_index(op.f('ix_threat_feeds_name'), 'threat_feeds', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_feeds_name'), table_name='threat_feeds')
    op.drop_index(op.f('ix_threat_feeds_id'), table_name='threat_feeds')
    op.drop_table('threat_feeds')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_type'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_id'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_cves_is_kev'), table_name='cves')
    op.drop_index(op.f('ix_cves_cve_id'), table_name='cves')
    op.drop_table('cves')
    # ### end Alembic commands ###
